# Generated by Django 3.2.5 on 2021-07-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210709_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notebooks',
            new_name='Notebook',
        ),
    ]
